name: Integracao continua

## Evento que dispara o workflow
on: 
  push:
    branches:
      - develop
      - master

jobs: 
  integracao:
    runs-on: self-hosted   
    permissions:
      contents: write  

    steps:
      - name: BaixarCodigo
        uses: actions/checkout@v4

      - name: Mark workspace as safe
        shell: powershell
        run: |
          git config --global --add safe.directory "$env:GITHUB_WORKSPACE"

      - name: Configurar Delphi
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Embarcadero\Studio\37.0\bin\rsvars.bat"

      - name: Build Projeto de Teste
        shell: cmd
        working-directory: Tests
        run: |
          msbuild EConn2026_Test.dproj /p:Config=Release /t:Build /p:DCC_ExeOutput=%GITHUB_WORKSPACE%\Bin\Tests

      - name: Build Projeto Principal
        shell: cmd
        working-directory: .\Fontes
        run: |
          msbuild EConn2026.dproj /p:Config=Release /t:Build /p:DCC_ExeOutput=%GITHUB_WORKSPACE%\Bin 