name: Integracao continua

## Evento que dispara o workflow
on: 
  push:
    branches:
      - develop
      - master

jobs: 
  integracao:
    runs-on: self-hosted     

    steps:
      - name: BaixarCodigo
        uses: actions/checkout@v4

      - name: Build Projeto de Teste
        shell: cmd
        working-directory: .\Tests
        run: |
          call "C:\Program Files (x86)\Embarcadero\Studio\37.0\bin\rsvars.bat"
          msbuild EConn2026_Test.dproj /p:Config=Release /t:Build /p:DCC_ExeOutput=%GITHUB_WORKSPACE%\Bin\Test

      - name: Build Projeto Principal
        shell: cmd
        working-directory: .\Fontes
        run: |
          msbuild EConn2026.dproj /p:Config=Release /t:Build /p:DCC_ExeOutput=%GITHUB_WORKSPACE%\Bin 